# 
# Basic
#
site_title: Blog Praderas
base_url: https://blog.praderas.org
rewrite_url: true

#
# Themes
#

theme: bootstrap-blog


# 
# Pagination
#

pagination_limit: 10
pagination_sub_page: true
pagination_page_indicator: "blog"
pagination_prev_text: "Entradas anteriores"
pagination_next_text: "Entradas recientes"

